# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
