# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_task_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='power',
            field=models.IntegerField(default=30),
        ),
    ]
