# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 14:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0005_auto_20161005_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wish_points_increase',
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 10, 7, 14, 41, 37, 341115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
