# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 09:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0006_auto_20161007_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 10, 11, 9, 54, 6, 976021, tzinfo=utc)),
        ),
    ]
