# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0008_auto_20161011_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 10, 11, 10, 11, 36, 699987, tzinfo=utc)),
        ),
    ]
