# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 13:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0013_auto_20161012_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 10, 12, 13, 31, 30, 44861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='avatar/', width_field='width_field'),
        ),
    ]
