# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 10:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0014_auto_20161012_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 11, 7, 10, 47, 48, 301088, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='avatar/avatar1.png', height_field='height_field', null=True, upload_to='avatar/', width_field='width_field'),
        ),
    ]
